<?php
use Drupal\Core\Routing\RouteMatchInterface;

/** Implements hook_help()
*
*/

function first_module_help($route_name, RouteMatchInterface $route_match) {

    switch ($route_name) {
        case 'help.page.first_module':
            $output = '';
            $output .= '<h3>' .t('About') . '</h3>';
            $output .= '<p>' . t('This is first help hook for custom module.') . '</p>';

        return $output;
        default:
    }

}