<?php

use Drupal\Core\Routing\RouteMatchInterface;

function link_module_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.link_module':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Link module for links') . '</p>';

            return $output;
        
        default:
    }
}